name: Check Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Setup dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Check Black formatting
      run: black --check .